include:
  - docker-compose.graylog.yml
  - docker-compose.keycloak.yml
  - docker-compose.metrics.yml

services:
  api:
    image: miguoliang/arch-go
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  kong-gateway:
    image: kong/kong-gateway
    command: bash -c "kong migrations bootstrap -v && kong start"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: postgres
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kong
    ports:
      - 5432:5432