services:
  iam:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    command: [ 'start-dev', '--http-relative-path=/auth' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /auth/health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 5s
      timeout: 2s
      retries: 15
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025