services:
  iam:
    image: quay.io/keycloak/keycloak:24.0.3
    command: [ 'start-dev', '--http-relative-path=/auth' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025