services:
  iam:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    command: [ 'start-dev', '--http-relative-path=/auth' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "--head","fsS", "http://localhost:8080/auth/health/ready" ]
      interval: 5s
      timeout: 2s
      retries: 15
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025