services:
  monitor:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  visualizer:
    image: grafana/grafana-oss
    ports:
      - 3000:3000