# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
          cache: 'true'

      - name: Build
        run: go build -v -o ./build/arch-go ./cmd/

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.keycloak.yml') }}

      - name: Prepare for testing
        run: docker-compose -f deployments/docker-compose.keycloak.yml up -d

      - name: Wait for health checks
        run: timeout 60s sh -c 'until docker ps | grep keycloak | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'

      - name: Test
        run: go test -v ./test
